version: "3"
services:
  verzekeren-backend:
    image: verzekeren-backend:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://verzekeren-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_GENERATE_DDL=true
    ports:
      - "8000:8000"
    depends_on:
      - "verzekeren-postgres"
    command: bash -c "sleep 10;"
    networks:
      - verzekeren

  verzekeren-postgres:
    image: postgres:9.3
    ports:
      - "5432"
    networks:
      - verzekeren
      
  verzekeren-frontend:
    image: verzekeren-frontend:latest
    ports:
      - "8080:80"
    networks:
      - verzekeren

networks:
  verzekeren:
