version: "3"
services:
  verzekeren-backend:
    image: verzekeren-backend:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://verzekeren-postgres:5432/verzekeren
      - SPRING_DATASOURCE_USERNAME=verzekeren
      - SPRING_DATASOURCE_PASSWORD=verzekeren
    ports:
      - "8000:8000"
    networks:
      - verzekeren

  verzekeren-postgres:
    image: postgres:9.3
    ports:
      - "5432"
    networks:
      - verzekeren

networks:
  verzekeren:
